In [1]:
import numpy as np

## DataTypes & Attributes


In [2]:
## Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])


a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
 a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.size

3

In [14]:
#Create a dataframe from numpy array

import pandas as pd

df = pd.DataFrame(a2)
df


0  1  2
0  1  2  3
1  4  5  6

## 2. Creating Arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2,3))
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype


dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((3,3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0,10, size=(3,5))

In [33]:
random_array


array([[9, 5, 7, 0, 0],
       [4, 4, 2, 9, 0],
       [4, 1, 6, 1, 8]])

In [34]:
random_array.size

15

In [35]:
random_array.shape

(3, 5)